teams = [
            {"id": "a", "name": "New England Patriots", "city": "Foxborough", "mascot": "Pat Patriot",
                  "found_year": 1959, "mascot_type": "human"},
            {"id": "b", "name": "Green Bay Packers", "city": "Green Bay", "mascot": "Packers", "found_year": 1919,
                  "mascot_type": "human"},
            {"id": "c", "name": "Dallas Cowboys", "city": "Dallas", "mascot": "Rowdy", "found_year": 1960,
                  "mascot_type": "human"},
            {"id": "d", "name": "Pittsburgh Steelers", "city": "Pittsburgh", "mascot": "Steely McBeam",
                  "found_year": 1933, "mascot_type": "human"},
            {"id": "e", "name": "San Francisco 49ers", "city": "San Francisco", "mascot": "Sourdough Sam",
                  "found_year": 1946, "mascot_type": "human"},
            {"id": "f", "name": "Kansas City Chiefs", "city": "Kansas City", "mascot": "K.C. Wolf",
                  "found_year": 1960, "mascot_type": "mammal"},
            {"id": "g", "name": "New York Giants", "city": "New York", "mascot": "No Mascot", "found_year": 1925,
                  "mascot_type": "none"},
            {"id": "h", "name": "Seattle Seahawks", "city": "Seattle", "mascot": "Blitz", "found_year": 1976,
                  "mascot_type": "bird"},
            {"id": "i", "name": "Denver Broncos", "city": "Denver", "mascot": "Miles", "found_year": 1960,
                  "mascot_type": "mammal"},
            {"id": "j", "name": "Chicago Bears", "city": "Chicago", "mascot": "Staley Da Bear",
                   "found_year": 1919, "mascot_type": "mammal"},
        ]